language: python
branches:
  only:
  - release
  - dev
python:
  - "2.7"
install:
  - cd ..
  - pip install git+ssh://git@github.com/nxt-dev/nxt.git
  - pip install ./nxt_editor

script:
  - python nxt/ci.py
