language: python
branches:
  only:
  - release
  - dev
python:
  - "2.7"
install:
  - cd ..
  - git clone --depth=50 --branch=release https://github.com/nxt-dev/nxt.git nxt-dev/nxt
  - pip install ./nxt
  - pip install ./nxt_editor

script:
  - python nxt/ci.py
