language: python
branches:
  only:
  - release
  - dev
python:
  - "3.7"

install:
  - cd ..
  - git clone git+ssh://git@github.com/nxt-dev/nxt.git
  - pip install ./nxt
  - pip install ./nxt_editor
  - export DISPLAY=:0.0

script:
  - python nxt/ci.py
